/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-tint": "#705d00",
              "on-error": "#ffffff",
              "on-secondary": "#ffffff",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#221b00",
              "on-secondary-fixed": "#1b1b1b",
              "on-background": "#1a1b22",
              "on-secondary-container": "#646464",
              "surface-variant": "#e3e1ec",
              "primary": "#705d00",
              "on-surface": "#1a1b22",
              "outline-variant": "#d0c6ab",
              "on-tertiary-fixed-variant": "#454748",
              "on-tertiary-container": "#5e5f60",
              "secondary-fixed-dim": "#c6c6c6",
              "on-error-container": "#93000a",
              "on-surface-variant": "#4d4732",
              "surface-container-high": "#e8e7f1",
              "primary-fixed-dim": "#e9c400",
              "tertiary": "#5d5e60",
              "inverse-on-surface": "#f1effa",
              "surface-bright": "#fbf8ff",
              "secondary-fixed": "#e2e2e2",
              "primary-container": "#ffd700",
              "on-secondary-fixed-variant": "#474747",
              "secondary": "#5e5e5e",
              "surface-container": "#eeedf7",
              "surface-dim": "#dad9e3",
              "on-primary-container": "#705e00",
              "error": "#ba1a1a",
              "error-container": "#ffdad6",
              "tertiary-fixed-dim": "#c6c6c7",
              "inverse-primary": "#e9c400",
              "secondary-container": "#e2e2e2",
              "tertiary-container": "#dadadb",
              "tertiary-fixed": "#e2e2e3",
              "outline": "#7e775f",
              "primary-fixed": "#ffe16d",
              "on-tertiary-fixed": "#1a1c1d",
              "surface-container-low": "#f4f2fd",
              "background": "#fbf8ff",
              "surface-container-lowest": "#ffffff",
              "inverse-surface": "#2f3038",
              "surface-container-highest": "#e3e1ec",
              "on-primary-fixed-variant": "#544600",
              "on-tertiary": "#ffffff",
              "surface": "#fbf8ff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "16px",
              "xl": "24px",
              "full": "9999px"
      },
      "spacing": {
              "md": "24px",
              "sm": "16px",
              "margin-mobile": "16px",
              "lg": "40px",
              "base": "4px",
              "xs": "8px",
              "gutter": "20px",
              "xl": "64px",
              "margin-desktop": "80px"
      },
      "fontFamily": {
              "headline-md": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "display-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
              "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
